-- ioncore.exec("/usr/bin/feh --bg-fill /home/emperor/pictures/background/plass-Planet-Simple-1152x2048.jpg")
-- ioncore.exec("/usr/bin/feh --bg-fill /home/emperor/pictures/background/look.com.ua-70003.jpg")
-- ioncore.exec("/usr/bin/feh --bg-fill /home/emperor/pictures/background/blue_dragon.jpg")
-- ioncore.exec("/usr/bin/feh --bg-fill /home/emperor/pictures/wallpaper/yin_yang_fire__water-wallpaper-1920x1080.jpg")
-- ioncore.exec("/usr/bin/feh --bg-fill /home/emperor/pictures/wallpaper/water_fire_elements-wallpaper-1920x1080.jpg")
ioncore.exec("/usr/bin/feh --bg-scale /home/emperor/pictures/wallpaper/TN6.jpg")
